package operator

import (
	"context"
	"errors"
	"time"

	"github.com/alexiosbluffmara/savitar/internal/gateway"
	"github.com/alexiosbluffmara/savitar/internal/memory"
)

// ErrNotImplemented marks the operator service as a planned backend surface
// until later passes wire real stores and review flows into it.
var ErrNotImplemented = errors.New("operator service method not implemented")

// RunSummary is the lightweight run view shown in an operator dashboard.
type RunSummary struct {
	ID              string
	Surface         gateway.Surface
	ConversationID  string
	StartedAt       time.Time
	Route           string
	ReferenceCount  int
	RequiresReview  bool
}

// ReviewItem is a pending operator action generated by the runtime.
type ReviewItem struct {
	ID             string
	Surface        gateway.Surface
	ConversationID string
	Reason         string
	Preview        string
	CreatedAt      time.Time
}

// Decision is the durable operator action recorded against a review item.
type Decision struct {
	ReviewID    string    `json:"reviewID"`
	OperatorID  string    `json:"operatorID"`
	Action      string    `json:"action"`
	Note        string    `json:"note"`
	DecidedAt   time.Time `json:"decidedAt"`
}

// Snapshot is the backend payload for an operator dashboard refresh.
type Snapshot struct {
	GeneratedAt    time.Time
	RecentRuns     []RunSummary
	PendingReviews int
	KnowledgePacks []memory.PackMeta
}

// Store is the durable backend behind the operator surface.
type Store interface {
	DashboardSnapshot(context.Context) (Snapshot, error)
	PendingApprovals(context.Context) ([]ReviewItem, error)
	RecordOperatorDecision(context.Context, Decision) error
}

// Service is the narrow backend entry point for the operator dashboard.
type Service struct {
	Store Store
	Clock func() time.Time
}

// Snapshot returns the current operator dashboard payload.
func (s Service) Snapshot(ctx context.Context) (Snapshot, error) {
	if s.Store == nil {
		return Snapshot{}, ErrNotImplemented
	}
	return s.Store.DashboardSnapshot(ctx)
}

// PendingReviews returns the current review queue.
func (s Service) PendingReviews(ctx context.Context) ([]ReviewItem, error) {
	if s.Store == nil {
		return nil, ErrNotImplemented
	}
	return s.Store.PendingApprovals(ctx)
}

// ApplyDecision records an operator action against one pending review item.
func (s Service) ApplyDecision(ctx context.Context, decision Decision) error {
	if s.Store == nil {
		return ErrNotImplemented
	}
	if decision.DecidedAt.IsZero() {
		now := time.Now
		if s.Clock != nil {
			now = s.Clock
		}
		decision.DecidedAt = now().UTC()
	}
	return s.Store.RecordOperatorDecision(ctx, decision)
}