#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel)"
SOURCE_FILE="$ROOT_DIR/docs/operations/internal-objectives-source.md"
OUTPUT_FILE="$ROOT_DIR/docs/operations/internal-objectives-board.md"

if [[ ! -f "$SOURCE_FILE" ]]; then
	echo "missing objectives source file: $SOURCE_FILE" >&2
	exit 1
fi

branch="$(git -C "$ROOT_DIR" branch --show-current 2>/dev/null || true)"
if [[ -z "$branch" ]]; then
	branch="detached-head"
fi

head_short="none"
head_subject="No commits yet"
if git -C "$ROOT_DIR" rev-parse --verify HEAD >/dev/null 2>&1; then
	head_short="$(git -C "$ROOT_DIR" rev-parse --short HEAD)"
	head_subject="$(git -C "$ROOT_DIR" log -1 --pretty=%s)"
fi

generated_at="$(date -u +"%Y-%m-%d %H:%M:%SZ")"

staged_count="$(git -C "$ROOT_DIR" diff --cached --name-only | wc -l | tr -d ' ')"
worktree_count="$(git -C "$ROOT_DIR" status --short | wc -l | tr -d ' ')"
go_file_count="$(find "$ROOT_DIR/cmd" "$ROOT_DIR/internal" -name '*.go' -print | wc -l | tr -d ' ')"
doc_file_count="$(find "$ROOT_DIR/docs" -name '*.md' -print | wc -l | tr -d ' ')"

render_block() {
	local title="$1"
	local command="$2"
	echo "## $title"
	local output
	output="$(eval "$command")"
	if [[ -z "$output" ]]; then
		echo "- none"
	else
		echo '```text'
		printf '%s\n' "$output"
		echo '```'
	fi
	echo
}

{
	echo "# Internal Objectives Board"
	echo
	printf '%s\n' '> Generated by `scripts/update-objectives-board.sh`. Update `docs/operations/internal-objectives-source.md` for long-lived direction changes.'
	echo
	echo "## Repo Snapshot"
	echo
	echo "- Generated at: $generated_at"
	echo "- Branch: $branch"
	echo "- HEAD: $head_short"
	echo "- HEAD subject: $head_subject"
	echo "- Staged paths: $staged_count"
	echo "- Worktree paths: $worktree_count"
	echo "- Go source files: $go_file_count"
	echo "- Markdown docs: $doc_file_count"
	echo
	render_block "Staged Changes" "git -C \"$ROOT_DIR\" diff --cached --name-status"
	render_block "Worktree Status" "git -C \"$ROOT_DIR\" status --short"
	render_block "Recent Commits" "git -C \"$ROOT_DIR\" log -5 --date=short --pretty=format:'%h %ad %s'"
	cat "$SOURCE_FILE"
	echo
} >"$OUTPUT_FILE"